sudo: required

service: docker
  
script:
  - docker build -t local/ci_cd .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag local/ci_cd $DOCKER_USERNAME/ci_cd:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USERNAME/ci_cd:$TRAVIS_BUILD_NUMBER
  - docker tag local/ci_cd $DOCKER_USERNAME/ci_cd:latest
  - docker push $DOCKER_USERNAME/ci_cd:latest
  - docker run -d -p 5000:5000 $DOCKER_USERNAME/ci_cd:latest
  - docker run $DOCKER_USERNAME/ci_cd:latest test
