sudo: required

service: docker
  
script:
  - docker build -t local/ci_cd .
after_success:
  - docker login -u $DOCKER_USER -p$DOCKER_PASSWORD
  - docker tag local/ci_cd $DOCKER_USER/ci_cd:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/ci_cd:$TRAVIS_BUILD_NUMBER
  - docker tag local/ci_cd $DOCKER_USER/ci_cd:latest
  - docker push $DOCKER_USER/ci_cd:latest

deploy:
  provider: script
  script: 
    - docker run -d -p 5000:5000 $DOCKER_USER/ci_cd:latest
    - curl localhost:5000
  on:
    branch: master
